### ISSUE TITLE
Armar plataforma de carga de calendario en googledrive

### ISSUE THREAD

**Issue by pablotis** [dnme-minturdep/calendario_dnmye#2]
Mantener Calendario desde allí para utilizar como insumo en script

**Comment by pablotis** [comment]
Pasamos a alimentar el calendario directo desde el servidor. Cierro acá.

**Comment by pablotis** [comment]
Verdad. Entonces tenemos que dejar acceso libre al sheet también, en modo lectura, para que no requiera mail de confirmación de forma manual en la consola, entiendo 🤔. Pruebo y vuelvo sobre esto.

**Comment by jpruiznicolini** [comment]
Fijate por acá que hay un workflow para el auth no interactivo https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by TuQmano** [comment]
Ya funcionando con GHA. Cierro
