### ISSUE TITLE
Agregar pestaña _calendario_ en todos YAML del SINTA

### ISSUE THREAD

**Issue by pablotis** [dnme-minturdep/calendario_dnmye#8]

**Comment by jpruiznicolini** [comment]
Esto ya está implementando en donde era posible: 

* armonizacion https://github.com/dnme-minturdep/armonizacion/commit/a59b0b43a32454004bb9d4a25e6ca16a34c009c4
* tableros https://github.com/dnme-minturdep/dnme_apps/commit/e5273aacc927d5b3c6bc8468a60bf2eb30f016f7
* bitacora https://github.com/dnme-minturdep/blog/commit/bf3ef2134152ebd80facef1558b46bc876a1b999
