### ISSUE TITLE
Revisar encabezado en pestaña de la página en el explorador

### ISSUE THREAD

**Issue by pablotis** [dnme-minturdep/calendario_dnmye#9]
![imagen](https://user-images.githubusercontent.com/30708601/159300039-801bfa89-96e9-4fe1-97d7-5e0df6824dcb.png)

**Comment by jpruiznicolini** [comment]
Fixed https://github.com/dnme-minturdep/calendario_dnmye/commit/82ab284064b127b67ab68c669343d1a00c983f9c
